### ISSUE TITLE
gap in histogram above x axis and below data bars in safari

### ISSUE THREAD

**Issue by mrjones-plip** [Packet-Clearing-House/Happy-Histogram#1]
steps to reproduce:

1. load a HH in safari

expected: bars are snug against x axis
actual: some bars have a 1px gap between them and x axis
workarounds: don't use safari :p

![gap](https://cloud.githubusercontent.com/assets/8253488/19989479/121c4136-a1e4-11e6-811f-c0f9ee4c235c.png)

**Comment by mrjones-plip** [comment]
I wonder if the renderer in safari doesn't like the bars having such high precision  heights for the bars?  Here's two that manifest the extra pixel:

``` html
<div class="bar" style="width: 3.4482758620689653%">
  <div class="emptyTop" style="height: 55.55555555555556%">&nbsp;</div>
  <div class="filledBottom" style="height: 44.44444444444444%">&nbsp;</div>
</div>

<div class="bar" style="width: 3.225806451612903%">
  <div class="emptyTop" style="height: 77.77777777777777%">&nbsp;</div>
  <div class="filledBottom" style="height: 22.22222222222222%">&nbsp;</div>
</div>
```

  something to test would be round to the closest 100th or even 10th.  width could be problematic too?

**Comment by melalj** [comment]
Have you tried to compute height in pixels instead of %  and round it to the closest pixel?
You can detect in JS the window size and the screen dpi ([http://stackoverflow.com/questions/476815/how-to-access-screen-display-s-dpi-settings-via-javascript](url))

**Comment by melalj** [comment]
Bonus: http://cruft.io/posts/percentage-calculations-in-ie/

**Comment by mrjones-plip** [comment]
@melalj  - awesome, thanks for the tips!  I'll look into them and report back.

**Comment by mrjones-plip** [comment]
OK - I have a nice simple test case that manifests the problem:

``` html
<div id="histogram"></div>
<script>
var Months  = [[4,9]]
HappyHistogram('histogram', Months);
</script>
```

Changing the `Months` array to be `[[1,9]]` still shows the problem, but `[[4,10]]` and it goes away.  This all supports our current working theory about the percent heights being the problem.  

stay tuned!

**Comment by mrjones-plip** [comment]
Hrm - I can't fully figure it, so I think I'm gonna do a partial fix.  If we get more complaints, we can open another ticket.  Or if @melalj thinks I'm wimping out too much, we can open another ticket ;)

Testing in safari, If I change this line:

``` javascript
bottom = day / max * 100;
```

to this so that we round to the closest 2:

``` javascript
bottom = Math.ceil((day / max * 100) / 2) * 2;
```

Everthing just works.  That is, until you zoom in.  Or until you use CSS to change the chart height to >50 or <50 than .  In both cases the gap comes back.  That said - the zooming and height problem existed before, just went unnoticed.

**Comment by mrjones-plip** [comment]
#2  PR fixes per comment above
